#!/bin/sh -x
# © Copyright 2008 IBM Corp.  All rights reserved.  
# This source code is made available under the terms of the Eclipse Public License, v1.0. 
find * -maxdepth 0 -type d -exec adb shell rm -r /data/'{}' ';'
