#!/bin/sh -x
# © Copyright 2008 IBM Corp.  All rights reserved.  
# This source code is made available under the terms of the Eclipse Public License, v1.0. 
find * -mindepth 1 -type f ! -path '*/.svn/*' -exec adb push '{}' /data/'{}' ';'
find * -type f -name '*.sh' -exec adb shell chmod 777 /data/'{}' ';'
